---
- name:Deploy to Tomcat
  hosts:web
  become:yes
  tasks:
     - name:Copy WAR files to Tomcat
       copy:
         src:"/var/snap/jenkins/4865/workspace/ansible-cicd/target/ansible1.war"
         dest:"/opt/tomcat/webapps/ansible1.war"
         remote_src:no
         
     - name:Restart Tomcat
         systemd:
            name:tomcat
            state:restarted
